sudo: false

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - export PATH=~/.local/bin/stack-0.1.5.0-x86_64-linux/:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libgmp-dev

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
